services:
  chain:
    image: ghcr.io/futureversecom/seed:00b0810
    command: ["--dev", "--unsafe-ws-external", --unsafe-rpc-external]
    ports:
      - "9933:9933"
      - "9944:9944"
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nikau-archive
    ports:
      - "5433:5432"

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:firesquid
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command:
      [
        "--database-url",
        "postgres://postgres:postgres@db:5432/porcini-archive",
        "--evm-support",
      ]
    ports:
      - "8888:8000"

volumes:
  postgres_data:
